services:
    app-local:
        build:
            context: .
            dockerfile: ./containers/app/app.local.dockerfile
        deploy:
            resources:
                limits:
                    cpus: '1'       # 1コアに制限
                    memory: 256M    # メモリを256MBに制限
        tty: true  # コンテナを起動したままにする
        env_file:
            - ./containers/app/.env
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./app:/app
        ports:
            - 8080:8080  # API
            - 8081:8081  # GoDoc
        networks:
            - backend
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: ./containers/db/db.dockerfile
        deploy:
            resources:
                limits:
                    cpus: '1'       # 1コアに制限
                    memory: 256M    # メモリを256MBに制限
        env_file:
            - ./containers/db/.env
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./containers/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
            - ./containers/db/data:/var/lib/postgresql
            - ./containers/db/backup:/var/lib/postgresql/backup
        ports:
            - 5432:5432
        networks:
            - backend

networks:
    backend:
        driver: bridge
