services:
    app-local:
        build:
            context: .
            dockerfile: ./infra/app/app.local.dockerfile
        tty: true  # コンテナを起動したままにする
        env_file:
            - ./infra/app/.env
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./app:/app
        ports:
            - 8080:8080  # API
            - 8081:8081  # GoDoc
        networks:
            - backend
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: ./infra/db/db.dockerfile
        env_file:
            - ./infra/db/.env
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./infra/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
            - ./infra/db/data:/var/lib/postgresql/data
            - ./infra/db/backup:/var/lib/postgresql/backup
        ports:
            - 5432:5432
        networks:
            - backend

networks:
    backend:
        driver: bridge
